#!/bin/sh
# Invoke the "rush prettier" custom command to reformat files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "prettier" autoinstaller.
node common/scripts/install-run-rush.js lint-staged || exit $?